/*
 * This source file was generated by the Gradle 'init' task
 */
package boardManager;
import java.sql.SQLException;

import boardManager.persistence.config.ConnectionConfig;
import boardManager.persistence.migration.MigrationStrategy;

public class App {
  
    public static void main(String[] args) throws SQLException {
        try(var connection = ConnectionConfig.getConnection()){
            new MigrationStrategy(connection).executeMigration();
        }
    }
}
