/*
 * This source file was generated by the Gradle 'init' task
 */
package boardManager;

import boardManager.ui.MainMenu;

public class App {
    public static void main(String[] args) throws Exception {
        new MainMenu().execute();
    }
}